from Common.StockOptions.Yahoo.YahooStockOption import YahooStockOption

yahooStockOption: YahooStockOption = YahooStockOption('CNI')
print("Source_fv: FinViz")
print("Name_fv:", yahooStockOption.FvCompanyName)
print("Sector_fv:", yahooStockOption.FvCompanySector)
print("Industry_fv:", yahooStockOption.FvCompanyIndustry)
print("Country_fv:", yahooStockOption.FvCompanyCountry)
print("MarketCap_fv:", yahooStockOption.FvMarketCap)
print("Beta_fv:", yahooStockOption.FvBeta)
print("PeRatio_fv:", yahooStockOption.FvPeRatio)
print("EPS_fv:", yahooStockOption.FvEPS)
print("EarningsDate_fv:", yahooStockOption.FvEarnings)
print("Low52_fv:", yahooStockOption.FvLow52)
print("High2_fv:", yahooStockOption.FvHigh52)
print("Range52_fv:", yahooStockOption.FvRange52)
print("Rsi14_fv:", yahooStockOption.FvRsi14)
print("Volatility_fv:", yahooStockOption.FvVolatility)
print("Ticker:", yahooStockOption.Ticker)
print("Link:", yahooStockOption.YahooSummaryScrapper.Link)
print("MarketCap:", yahooStockOption.YahooSummaryScrapper.MarketCap)
print("Beta:", yahooStockOption.YahooSummaryScrapper.Beta)
print("PEratio:", yahooStockOption.YahooSummaryScrapper.PEratio)
print("EPS:", yahooStockOption.YahooSummaryScrapper.EPS)
print("EarningsDate:", yahooStockOption.YahooSummaryScrapper.EarningsDate)
print(yahooStockOption.HistoricalData.describe(include='all'))
