from Common.StockOptions.Yahoo.YahooStockOption import YahooStockOption
from Common.Readers.Engine.YahooFinEngine import YahooFinEngine

yahooStockOption: YahooStockOption = YahooStockOption('TD')
print("Source_fv: FinViz")
print("Url_ye:", yahooStockOption.YeUrl)
print("LogoUrl_ye:", yahooStockOption.YeLogoUrl)
print("Address_ye:", yahooStockOption.YeAddress)
print("City_ye:", yahooStockOption.YeCity)
print("State_ye:", yahooStockOption.YeState)
print("PostalCode_ye:", yahooStockOption.YePostalCode)
print("Country_ye:", yahooStockOption.YeCountry)
print("Beta_ye:", yahooStockOption.YeBeta)
print("Market_ye:", yahooStockOption.YeMarket)
print("Exchange_ye:", yahooStockOption.YeExchange)
print("Currency_ye:", yahooStockOption.YeCurrency)
print("QuoteType_ye:", yahooStockOption.YeQuoteType)
print("52WeekHigh_ye:", yahooStockOption.YeHigh52)
print("52WeekLow_ye:", yahooStockOption.YeLow52)
print("50DayAverage_ye:", yahooStockOption.YeAverage50)
print("200DayAverage_ye:", yahooStockOption.YeAverage200)
print("MarketCap_ye:", yahooStockOption.YeMarketCap)
print("PayoutRatio_ye:", yahooStockOption.YePayoutRatio)
print("PeForward_ye:", yahooStockOption.YePeForward)
print("PeTrailing_ye:", yahooStockOption.YePeTrailing)
print("PegRatio_ye:", yahooStockOption.YePegRatio)
print("ShortRatio_ye:", yahooStockOption.YeShortRatio)
print("BookValue_ye:", yahooStockOption.YeBookValue)
print("PriceToBook_ye:", yahooStockOption.YePriceToBook)
print("ExDividendDate_ye:", yahooStockOption.YeExDividendDate)
print("Ticker:", yahooStockOption.Ticker)
print("Link_yss:", yahooStockOption.YssLink)
print("MarketCap_yss:", yahooStockOption.YssMarketCap)
print("Beta_yss:", yahooStockOption.YssBeta)
print("PEratio_yss:", yahooStockOption.YssPeRatio)
print("EPS_yss:", yahooStockOption.YssEPS)
print("EarningsDate_yss:", yahooStockOption.YssEarningsDate)
print(yahooStockOption.DataFrame.describe(include='all'))
yahooFinEngine: YahooFinEngine = YahooFinEngine('TD')
print("Yahoo Finance - Analysis")
print("Yahoo Finance - Analysis - EarningsHistory")
print(yahooFinEngine.AnalyseEarningsHistoryDf)
print("Yahoo Finance - Analysis - EarningsEstimate")
print(yahooFinEngine.AnalyseEarningsEstimateDf)
print("Yahoo Finance - Analysis - EPSRevisions")
print(yahooFinEngine.AnalyseEPSRevisionsDf)
print("Yahoo Finance - Analysis - RevenueEstimate")
print(yahooFinEngine.AnalyseRevenueEstimateDf)
print("Yahoo Finance - Financials")
print("Yahoo Finance - Financials - IncomeStatement")
print(yahooFinEngine.IncomeStatementDf)
print("Yahoo Finance - Financials - BalanceSheet")
print(yahooFinEngine.BalanceSheetDf)
print("Yahoo Finance - Financials - CashFlow")
print(yahooFinEngine.CashFlowDf)
