# -*- coding: utf-8 -*-
"""Vizualizations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3h6NR8cmJxLbIYpLF77LOq3eArgreA4
"""



import matplotlib.pyplot as plt
time = [0, 1, 2, 3]
position = [0, 100, 200, 300]
plt.plot(time, position)
plt.xlabel('Time (hr)')
plt.ylabel('Position (km)')

import pandas as pd
import random
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.DataFrame()
df['x'] = random.sample(range(1, 100), 25)
df['y'] = random.sample(range(1, 100), 25)
df.head()

"""scatterplot"""

sns.lmplot('x', 'y', data=df, fit_reg=False)

"""density plot"""

sns.kdeplot(df.y)

"""v2"""

sns.kdeplot(df.y, df.x)

"""v3"""

sns.distplot(df.x)

"""Histogram"""

plt.hist(df.x, alpha=.3)
sns.rugplot(df.x);

"""Boxplot"""

sns.boxplot([df.y, df.x])

"""Violin"""

sns.violinplot([df.y, df.x])

"""Heatmap"""

sns.heatmap([df.y, df.x], annot=True, fmt="d")

"""Clustermap"""

sns.clustermap(df)